### PR TITLE
Lint `eslint-config-sheriff` with `eslint-config-sheriff`

### PR DESCRIPTION
**Pull request by lishaduck**

### CODE REVIEW

**Comment by AndreaPontrandolfo** [comment]
I think we need to wait for https://github.com/AndreaPontrandolfo/sheriff/pull/161 before tackling this PR.

**Comment by lishaduck** [comment]
> I think we need to wait for #161 before tackling this PR.

There's not a direct dependency, but as I don't have it cloned, I'm fine to wait.

**Comment by lishaduck** [comment]
This's collected a bunch of conflicts, so I'm closing in favor of #236.
I'll probably rewrite it someday, but I'm busy on some work over in elm-review (and school started back up), so it's not high on my todo list.
I want to express my gratitude for sheriff real quick though, it's been great to be able to come help out (and it's an amazingly done preset as well).

**Comment by AndreaPontrandolfo** [comment]
@lishaduck i wish you good luck on `elm-review` and school! I'm sure you will rock it!!
Come back here whenever you feel like it!

> I want to express my gratitude for sheriff real quick though, it's been great to be able to come help out (and it's an amazingly done preset as well).

Likewise, i thank you!!

**Pull request closed without merging**
