### PR TITLE
Fix `getRequiredPackages` for ts-patch

### PR DESCRIPTION
**Pull request by nahtnam**
Bug was introduced in this commit: https://github.com/AndreaPontrandolfo/sheriff/commit/0a9e1f44180fa2a318481f66e195cfeed40da13a

### CODE REVIEW

**Comment by nahtnam** [comment]
cc @AndreaPontrandolfo

**Comment by nahtnam** [comment]
It might be worthwhile to run the cli in a test

**Comment by AndreaPontrandolfo** [comment]
Hey @nahtnam , thanks for the report!

Did you encounter this bug only in the latest master, still unreleased?

**Comment by AndreaPontrandolfo** [comment]
After releasing version https://github.com/AndreaPontrandolfo/sheriff/releases/tag/eslint-config-sheriff%4020.0.0, i can confirm that this bug is indeed happening.
Will merge this soon.

**Review by AndreaPontrandolfo — APPROVED** [review]

**Pull request merged**
